# Generated by Django 4.1.7 on 2023-06-13 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0051_delete_datasciencetraining_functionmeta_test_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('execution_mode', models.CharField(choices=[('TRAINING', 'Training'), ('EXECUTION', 'Execution')], default='TRAINING', max_length=64)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rapidiamapp.entity')),
                ('function', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rapidiamapp.functionmeta')),
            ],
        ),
        migrations.CreateModel(
            name='DerivedDataScienceArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument_name', models.CharField(max_length=30, null=True)),
                ('argument_value', models.TextField(null=True)),
                ('argument_type', models.CharField(max_length=30, null=True)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rapidiamapp.datascience')),
            ],
        ),
    ]
