# Generated by Django 4.1.7 on 2023-06-15 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0052_datascience_deriveddatascienceargument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argumentmeta',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='rapidiamapp.functionmeta'),
        ),
    ]
