# Generated by Django 4.1.7 on 2023-06-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0053_alter_argumentmeta_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityChildren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_field_id', models.IntegerField(null=True)),
                ('child_field_id', models.IntegerField(null=True)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rapidiamapp.entitychildren')),
            ],
        ),
    ]
