# Generated by Django 4.1.7 on 2023-06-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0055_remove_entitychildren_entity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitychildren',
            name='child_field_id',
        ),
        migrations.RemoveField(
            model_name='entitychildren',
            name='parent_field_id',
        ),
        migrations.AddField(
            model_name='entitychildren',
            name='child_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_field', to='rapidiamapp.field'),
        ),
        migrations.AddField(
            model_name='entitychildren',
            name='parent_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_field', to='rapidiamapp.field'),
        ),
    ]
