# Generated by Django 4.1.7 on 2023-06-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0057_entitychildren_child_entity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='child_entity_id',
        ),
        migrations.RemoveField(
            model_name='field',
            name='child_field_id',
        ),
    ]
