# Generated by Django 4.1.7 on 2023-06-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0058_remove_field_child_entity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='child_entity_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='child_field_id',
            field=models.IntegerField(null=True),
        ),
    ]
