# Generated by Django 4.1.7 on 2023-06-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0059_field_child_entity_id_field_child_field_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='child_entity_id',
        ),
        migrations.RemoveField(
            model_name='field',
            name='child_field_id',
        ),
        migrations.AddField(
            model_name='field',
            name='entity_field_name',
            field=models.CharField(default='', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
