# Generated by Django 4.1.7 on 2023-06-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0063_alter_entitychildren_child_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
