# Generated by Django 4.1.7 on 2023-06-19 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0064_alter_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAlertFieldFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_col', models.CharField(max_length=30)),
                ('filter_op', models.CharField(choices=[('eq', 'Exact'), ('not', 'Not'), ('gt', 'Greater Than'), ('gte', 'Greater Than Equal To'), ('lt', 'Less Than'), ('lte', 'Less Than Equal')], default='EXACT', max_length=30)),
                ('filter_val', models.CharField(max_length=120)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapidiamapp.entity')),
            ],
        ),
    ]
