# Generated by Django 4.1.7 on 2023-06-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0065_dataalertfieldfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataalertfieldfilter',
            name='callback_url',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataalertfieldfilter',
            name='sched_min',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
