# Generated by Django 4.1.7 on 2023-06-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0066_dataalertfieldfilter_callback_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataalertfieldfilter',
            old_name='callback_url',
            new_name='callback_url1',
        ),
    ]
