# Generated by Django 4.1.7 on 2023-06-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0068_rename_callback_url1_dataalertfieldfilter_callback_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataalertfieldfilter',
            name='sched_min',
            field=models.IntegerField(default=0),
        ),
    ]
