# Generated by Django 4.1.7 on 2023-06-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0069_alter_dataalertfieldfilter_sched_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_sql', models.TextField()),
                ('sched_min', models.IntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapidiamapp.entity')),
            ],
        ),
    ]
