# Generated by Django 4.1.7 on 2023-06-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0070_schedulejob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataalertfieldfilter',
            name='callback_url',
        ),
        migrations.RemoveField(
            model_name='dataalertfieldfilter',
            name='sched_min',
        ),
        migrations.AddField(
            model_name='schedulejob',
            name='scallback_url',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
