# Generated by Django 4.1.7 on 2023-06-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0072_rename_scallback_url_schedulejob_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulejob',
            name='last_run',
            field=models.DateTimeField(null=True),
        ),
    ]
