# Generated by Django 4.1.7 on 2023-06-19 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0073_schedulejob_last_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulejob',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
