# Generated by Django 4.1.7 on 2023-07-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0075_alter_schedulejob_last_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='schedulejob',
            name='last_run',
            field=models.DateTimeField(),
        ),
    ]
