# Generated by Django 4.1.7 on 2023-08-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0077_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='folder_path',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
