# Generated by Django 4.1.7 on 2023-08-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidiamapp', '0078_entity_folder_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='folder_path',
            field=models.CharField(max_length=1024),
        ),
    ]
